version: '3'
services:
  client:
    container_name: angular
    build: client
    ports:
      - "4200:4200"

  server:
    container_name: express
    restart: always
    build: server
    ports:
      - '80:3000'
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
